const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
function setup(){const cache=new Map();function load(name){const p=path.resolve(name);if(cache.has(p))return cache.get(p);const out={};cache.set(p,out);const source=ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','exports',source)(n=>n.startsWith('.')?load(path.resolve(path.dirname(p),n+'.ts')):require(n),out);return out}return {m:load('src/domain/model.ts'),d:load('src/data/demo.ts')}}
test('一括確定の重複エラーでは全件未変更、問題のない選択はまとめて確定',()=>{const {m,d}=setup();d.demoLogin('admin','demo1234');const id=m.periodOf(m.today());const w=d.readDemo(id),target=w.shifts.filter(s=>s.employeeId==='e1');assert.throws(()=>d.commandDemo(id,{type:'setStatus',ids:target.map(s=>s.id),status:'confirmed'}),/全件の確定を中止/);assert.deepEqual(d.readDemo(id).shifts,w.shifts);const ids=target.slice(0,3).map(s=>s.id);d.commandDemo(id,{type:'setStatus',ids,status:'confirmed'});assert.equal(d.readDemo(id).shifts.filter(s=>ids.includes(s.id)&&s.status==='confirmed').length,3);assert.throws(()=>d.commandDemo(id,{type:'setStatus',ids:[target[3].id],status:'confirmed'}),/全件の確定を中止/)});
test('確定済みは直接編集不可、未確定へ戻して修正。見送りからも戻せる',()=>{const {m,d}=setup();d.demoLogin('admin','demo1234');const id=m.periodOf(m.today());const s=d.readDemo(id).shifts.find(s=>s.status==='confirmed');assert.throws(()=>d.commandDemo(id,{type:'saveShift',shift:s,acknowledgeOverlap:true}),/未確定に戻して/);d.commandDemo(id,{type:'setStatus',ids:[s.id],status:'pending'});d.commandDemo(id,{type:'saveShift',shift:{...s,note:'調整'},acknowledgeOverlap:true});d.commandDemo(id,{type:'setStatus',ids:[s.id],status:'declined'});d.commandDemo(id,{type:'setStatus',ids:[s.id],status:'pending'});assert.equal(d.readDemo(id).shifts.find(r=>r.id===s.id).note,'調整');assert.notEqual(d.readDemo(id).shifts.find(r=>r.id===s.id).original.note,'調整')});
test('下書きと提出を分離し、空欄全日を休みとして再提出できる',()=>{const {m,d}=setup();const id=m.movePeriod(m.periodOf(m.today()),1);d.demoEmployee('e1');const old=d.readDemo(id).submissions[0];d.commandDemo(id,{type:'saveDraft',rows:[],note:'全日休み希望'});d.demoLogin('admin','demo1234');let w=d.readDemo(id);assert.equal(w.shifts.filter(s=>s.employeeId==='e1').length,old.submittedRows.length);assert.equal(w.submissions[0].draftRows.length,0);d.demoEmployee('e1');d.commandDemo(id,{type:'submit',acknowledgeOverlap:true});assert.ok(d.readDemo(id).submissions[0].submittedAt);assert.equal(d.readDemo(id).submissions[0].submittedRows.length,0);d.demoLogin('admin','demo1234');assert.equal(d.readDemo(id).shifts.filter(s=>s.employeeId==='e1').length,0)});
test('締切後の従業員変更禁止、本人以外の閲覧と管理者操作を禁止',()=>{const {m,d}=setup();const id=m.periodOf(m.today());d.demoEmployee('e1');const w=d.readDemo(id);assert.equal(w.shifts.length,0);assert.equal(w.employees.length,1);assert.ok(w.submissions.every(s=>s.employeeId==='e1'));assert.throws(()=>d.commandDemo(id,{type:'saveDraft',rows:[],note:''}),/受付が終了/);assert.throws(()=>d.commandDemo(id,{type:'setStatus',ids:['x'],status:'confirmed'}),/管理者のみ/)});
test('15分単位・日付またぎ・割り当て範囲の入力制約、境界の接続は重複なし',()=>{const {m}=setup();const p=m.makePeriod('2026-10-01'),r={id:'a',date:'2026-10-03',start:'09:00',end:'12:00',floorId:'f1',note:''};assert.doesNotThrow(()=>m.validateRow(r,p,['f1']));assert.throws(()=>m.validateRow({...r,start:'09:10'},p,['f1']));assert.throws(()=>m.validateRow({...r,start:'22:00',end:'05:00'},p,['f1']));assert.throws(()=>m.validateRow({...r,end:'09:00'},p,['f1']));assert.throws(()=>m.validateRow({...r,floorId:'f2'},p,['f1']));assert.equal(m.overlaps(r,{...r,id:'b',start:'12:00',end:'17:00'}),false);assert.equal(m.daysOf(m.makePeriod('2028-02-16')).length,14)});
test('重複希望は確認前には提出不可、確認後は可能。締切前の確定は仮仕様として禁止',()=>{const {m,d}=setup();const id=m.movePeriod(m.periodOf(m.today()),1);d.demoEmployee('e1');assert.throws(()=>d.commandDemo(id,{type:'submit',acknowledgeOverlap:false}),/重複/);d.commandDemo(id,{type:'submit',acknowledgeOverlap:true});d.demoLogin('admin','demo1234');assert.throws(()=>d.commandDemo(id,{type:'setStatus',ids:[d.readDemo(id).shifts[0].id],status:'confirmed'}),/仮ルール/)});
test('タイムライン人数：複数シフトの同一人物を重複除外し、終了時刻は人数から外す',()=>{const {m}=setup();const rows=[{employeeId:'a',start:'09:00',end:'12:00'},{employeeId:'a',start:'10:00',end:'13:00'},{employeeId:'b',start:'12:00',end:'15:00'}];assert.equal(m.headcount(rows),2);assert.equal(m.headcount(rows,600,615),1);assert.equal(m.headcount(rows,720,735),2);assert.equal(m.headcount(rows,780,795),1);assert.equal(m.headcount(rows,900,915),0);assert.equal(m.headcount(rows.map(s=>s.employeeId==='b'?{...s,start:'13:00'}:s),720,735),1);assert.equal(m.headcount([]),0)});
